name: check_code_quality
on: pull_request
jobs:
  black:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - run: |
          python -m pip install --upgrade pip
          pip install black
      - run: |
          # Find all non-ipynb files and run black on them
          git ls-files '*.py' | xargs black --check --verbose
  pylint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4 
        with:
          python-version: 3.11
      - run: |
          python -m pip install --upgrade pip
          pip install pylint
      - run: |
          # Find all non-ipynb files and run pylint on them
          git ls-files '*.py' | xargs pylint --check --verbose
